baseURL = "https://blog.penguwin.eu/"
title = "penguwin"
languagecode = "en"
author = "Nicolas Martin"
copyright = "Copyright © 2019-2020" #supports html markup
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
#googleAnalytics = "UA-123-45"
# disqusShortname = "yourdiscussshortname"
theme = "monopriv"
enableEmoji = true
summaryLength = 20

[params]
about = "Failure is not an Option<T> its a Result<T, E>"
github = "https://github.com/penguwin"
email = "penguwin@penguwin.eu"
# site meta description
metadesc = "yet another personal blog"
# site meta keywords
metakeys = "hugo, bootstrap, blog"
# enable/disable disqus comments
disqus = false
# enable/disable google analytics
analytics = false

# [params.search] # Site search powered by DuckDuckGo
# enabled = true
# placeholder="Site Search"

[params.hero]
enabled = true
img = "img/avatar.jpg"
